### ISSUE TITLE
Nanya om

### ISSUE THREAD

**Issue by deerookie** [wildantea/feederimporter#1]
Di FeederImporter bikinannya om, saya berniat input nilai.
 Kronologisx :)  ;
   > Upload file excel 60 baris data
   > Upload ke importer sukses.
   > Import ke Feeder, muncul pesan limit waktu.
   > cek di Importer, 33 data status sukses, tapi di Feeder, hanya 30 data yang masuk.
sekian om..
anyway webnya keren om, saluut. : +1:

**Comment by wildantea** [comment]
timeout di lamain om, edit php.ini kemudian cari max_execution_time
ubah yang tadinya 30 detik jadi 5000 misal.

**Comment by deerookie** [comment]
Sipp omm.. My main issue selama ini.. Terima kasih banyak om
